[package]
name = "cubo"
version = "0.1.0"
edition = "2021"

[dependencies]
minifb = "0.28"
nalgebra = "0.34"
image = "0.25"  # Para cargar texturas
rayon = "1.7"


# Optimizaciones para mejor rendimiento
[profile.dev]
opt-level = 2  

[profile.release]
opt-level = 3 
lto = true   